### ISSUE TITLE
Update Firebase to 11.0

### ISSUE THREAD

**Issue by agusmarkosich8** [segment-integrations/analytics-swift-firebase#27]

**Comment by alanjcharles** [comment]
Hi @agusmarkosich8 ! In order to streamline the reporting and escalation process internally, we are disabling Github Issues for this repository. If you are still experiencing this issue please send a copy of your report, as well as any other information you might have, to `friends@segment.com`  so we can prioritize it accordingly. Thanks and apologies for the inconvenience!
